import type { CSSProperties } from "react";

export const s = {
  split: { display: "flex", height: "100%", minHeight: 480 } satisfies CSSProperties,
  list: {
    width: 320,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
    display: "flex",
    flexDirection: "column",
  } satisfies CSSProperties,
  listHead: { padding: "14px 14px 10px" } satisfies CSSProperties,
  listTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-muted)",
    letterSpacing: "0.04em",
    marginBottom: 4,
  } satisfies CSSProperties,
  listPattern: {
    fontSize: 11.5,
    color: "var(--text-secondary)",
    marginBottom: 12,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  listActions: { display: "flex", gap: 4 } satisfies CSSProperties,
  iconBtn: {
    width: 30,
    height: 30,
    display: "inline-grid",
    placeItems: "center",
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  rows: { flex: 1, overflow: "auto", padding: "0 8px 8px" } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "7px 9px",
    borderRadius: 6,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  rowActive: { background: "var(--bg-hover)", color: "var(--text-primary)" } satisfies CSSProperties,
  rowText: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 1,
  } satisfies CSSProperties,
  rowName: {
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowDir: {
    fontSize: 11,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  usedBy: { display: "inline-flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  pane: { flex: 1, display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  paneHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 20px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  paneRight: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  skeletonStack: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "20px 28px",
  } satisfies CSSProperties,
} as const;
